//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajon
    {
        public int id_cjn { get; set; }
        public string nombre_cjn { get; set; }
        public int piso_cjn { get; set; }
    }
}
