//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamientoEntities : DbContext
    {
        public EstacionamientoEntities()
            : base("name=EstacionamientoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cajon> Cajon { get; set; }
        public virtual DbSet<Entradas> Entradas { get; set; }
        public virtual DbSet<Registros> Registros { get; set; }
        public virtual DbSet<Salidas> Salidas { get; set; }
    }
}
