//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas
    {
        public int id_sld { get; set; }
        public int id_reg { get; set; }
        public System.DateTime salida { get; set; }
    }
}
